# Generated by Django 4.1.3 on 2022-12-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_personaje_characterid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(db_column='id_mascota', primary_key=True, serialize=False)),
                ('fecha_cumpleaños', models.DateField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('edad', models.CharField(blank=True, max_length=10, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(db_column='id_productos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('stock', models.CharField(blank=True, max_length=20)),
                ('Precio', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_cuenta', models.AutoField(db_column='id_cuenta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
    ]
