# Generated by Django 4.1.3 on 2022-12-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_mascotas_productos_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='carroCompra',
            fields=[
                ('id_compra', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('producto', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=999)),
                ('precio', models.CharField(max_length=99)),
                ('stock', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('producto', models.CharField(max_length=99)),
                ('descripcion', models.CharField(max_length=999)),
                ('precio', models.CharField(max_length=99)),
                ('stock', models.CharField(max_length=99)),
            ],
        ),
        migrations.DeleteModel(
            name='Mascotas',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
