# Generated by Django 4.1.3 on 2022-12-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_carrocompra_producto_delete_mascotas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_ClienteVenta', models.AutoField(db_column='id_ClienteVenta', primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_descripcion', models.AutoField(db_column='id_descripcion', primary_key=True, serialize=False)),
                ('descripcionVenta', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('productoVenta', models.CharField(max_length=99)),
                ('precioVenta', models.CharField(max_length=99)),
                ('stockComprado', models.CharField(max_length=99)),
            ],
        ),
        migrations.RenameField(
            model_name='carrocompra',
            old_name='descripcion',
            new_name='descripcionCompra',
        ),
        migrations.RenameField(
            model_name='carrocompra',
            old_name='foto',
            new_name='fotoCompra',
        ),
        migrations.RenameField(
            model_name='carrocompra',
            old_name='precio',
            new_name='precioCompra',
        ),
        migrations.RenameField(
            model_name='carrocompra',
            old_name='producto',
            new_name='productoCompra',
        ),
        migrations.RenameField(
            model_name='carrocompra',
            old_name='stock',
            new_name='stockCompra',
        ),
    ]
