# Generated by Django 4.1.3 on 2022-12-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_cliente_detalle_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaje',
            name='id_personaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
